name: copy files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: copy file
      uses: canastro/copy-file-action@master
      with:
        source: "Info.md"
        target: "Readme.md"
